### PR TITLE
Add "Retro" health bar style

### PR DESCRIPTION
**Pull request by LukeDarling**

### CODE REVIEW

**Comment by LukeDarling** [comment]
What should I name it?

**Comment by iksaku** [comment]
Hmmm Bars... Horizontal? xD

**Comment by LukeDarling** [comment]
flatline

**Comment by iksaku** [comment]
maybe :P

**Comment by PEMapModder** [comment]
@LukeDarling You have been added to the team @LegendOfMCPE/healthbar. Please edit directly now.

**Pull request merged**
