### PR TITLE
Use WeakRef for EssentialsPE reference, fixing bugs.

### PR DESCRIPTION
**Pull request by PEMapModder**
@iksaku: Is that field even **used**?

@iksaku Merge this, although I can do it myself :P

### CODE REVIEW

**Comment by iksaku** [comment]
Sorry, but this isn't needed, it works well with or without EssentialsPE

**Comment by PEMapModder** [comment]
Yes, because you didn't use that field at all. Anyway, that line is **ABSOLUTELY** wrong.

**Comment by iksaku** [comment]
Test it, it doesn't have any bugs yet (referencing to that way to connect to EssPE)

**Comment by PEMapModder** [comment]
I said, it doesn't cause any visible bugs because it just makes an unnecessary object stored in the memory, wasting maybe half a kilobyte in the RAM for a new \EssentialsPE\Loader object.

**Comment by iksaku** [comment]
Check it, onEnable() it checks if there's a plugin called "EssentialsPE" and it's loaded, if yes store it on the object :P

-----Mensaje original-----
De: PEMapModder
Enviado: 09/08/2014 10:47 a.m.
Para: LegendOfMCPE/HealthBar
CC: Jorge González
Asunto: Re: [HealthBar] Use WeakRef for EssentialsPE reference,fixing bugs. (#10)

I said, it doesn't cause any visible bugs because it just makes an unnecessary object stored in the memory, wasting maybe half a kilobyte in the RAM.

**Comment by iksaku** [comment]
This is nothing to complain about, I think, else it may got disapproved by humerusj :/

-----Mensaje original-----
De: PEMapModder
Enviado: 09/08/2014 10:47 a.m.
Para: LegendOfMCPE/HealthBar
CC: Jorge González
Asunto: Re: [HealthBar] Use WeakRef for EssentialsPE reference,fixing bugs. (#10)

I said, it doesn't cause any visible bugs because it just makes an unnecessary object stored in the memory, wasting maybe half a kilobyte in the RAM.

**Comment by PEMapModder** [comment]
@iksaku Check. You said

> if yes store it on the object

But are you sure you stored _**it**_? Well, I am sorry to say this, but do some research in PHP objects first.

**Comment by PEMapModder** [comment]
@iksaku:

``` php
if($foo instanceof Foo){
    $this->bar = $foo;
}
```

is different from

``` php
if($foo instanceof Foo){
    $this->bar = new Foo();
}
```

**Pull request closed without merging**
