### PR TITLE
added support for API 1.4.0

### PR DESCRIPTION
**Pull request by LukeDarling**
API 1.4.0 removes the need to reference EntityDamageByEntityEvent.

### CODE REVIEW

**Comment by iksaku** [comment]
Then how we will prevent PvP? please take a look at @PEMapModder work on EssentialsPE and add it to the pull ;)

BTW: You can directly commit to fix issues :D

**Comment by LukeDarling** [comment]
```
2014-09-06 19:54:39 [NOTICE] An E_RECOVERABLE_ERROR error happened: "Argument 1 passed to HealthBar\EventHandler::onAttack() must be an instance of pocketmine\event\entity\EntityDamageByEntityEvent, instance of pocketmine\event\entity\EntityDamageEvent given, called in phar:///home/luke/pm1.4/PocketMine-MP.phar/src/pocketmine/plugin/MethodEventExecutor.php on line 36 and defined" in "/HealthBar-master/src/HealthBar/EventHandler" at line 52
2014-09-06 19:55:08 [NOTICE] An E_RECOVERABLE_ERROR error happened: "Argument 1 passed to HealthBar\EventHandler::onAttack() must be an instance of pocketmine\event\entity\EntityDamageByEntityEvent, instance of pocketmine\event\entity\EntityDamageEvent given, called in phar:///home/luke/pm1.4/PocketMine-MP.phar/src/pocketmine/plugin/MethodEventExecutor.php on line 36 and defined" in "/HealthBar-master/src/HealthBar/EventHandler" at line 52
2014-09-06 19:55:19 [NOTICE] An E_RECOVERABLE_ERROR error happened: "Argument 1 passed to HealthBar\EventHandler::onAttack() must be an instance of pocketmine\event\entity\EntityDamageByEntityEvent, instance of pocketmine\event\entity\EntityDamageEvent given, called in phar:///home/luke/pm1.4/PocketMine-MP.phar/src/pocketmine/plugin/MethodEventExecutor.php on line 36 and defined" in "/HealthBar-master/src/HealthBar/EventHandler" at line 52
2014-09-06 19:55:38 [NOTICE] An E_RECOVERABLE_ERROR error happened: "Argument 1 passed to HealthBar\EventHandler::onAttack() must be an instance of pocketmine\event\entity\EntityDamageByEntityEvent, instance of pocketmine\event\entity\EntityDamageEvent given, called in phar:///home/luke/pm1.4/PocketMine-MP.phar/src/pocketmine/plugin/MethodEventExecutor.php on line 36 and defined" in "/HealthBar-master/src/HealthBar/EventHandler" at line 52
2014-09-06 19:55:59 [NOTICE] An E_RECOVERABLE_ERROR error happened: "Argument 1 passed to HealthBar\EventHandler::onAttack() must be an instance of pocketmine\event\entity\EntityDamageByEntityEvent, instance of pocketmine\event\entity\EntityDamageEvent given, called in phar:///home/luke/pm1.4/PocketMine-MP.phar/src/pocketmine/plugin/MethodEventExecutor.php on line 36 and defined" in "/HealthBar-master/src/HealthBar/EventHandler" at line 52
2014-09-06 19:56:12 [NOTICE] An E_RECOVERABLE_ERROR error happened: "Argument 1 passed to HealthBar\EventHandler::onAttack() must be an instance of pocketmine\event\entity\EntityDamageByEntityEvent, instance of pocketmine\event\entity\EntityDamageEvent given, called in phar:///home/luke/pm1.4/PocketMine-MP.phar/src/pocketmine/plugin/MethodEventExecutor.php on line 36 and defined" in "/HealthBar-master/src/HealthBar/EventHandler" at line 52
```

**Comment by LukeDarling** [comment]
"BTW: You can directly commit to fix issues :D"

No I can't. I'm the only one of us who's not an owner. :P
https://github.com/orgs/LegendOfMCPE/people

**Comment by iksaku** [comment]
@LukeDarling You're now on the team ;)

**Comment by PEMapModder** [comment]
This is not the way to fix the issue.

**Comment by PEMapModder** [comment]
Oops wait you are right.

**Comment by PEMapModder** [comment]
@LukeDarling why are you not in the org?

**Comment by iksaku** [comment]
Because I invited him but he reject the invitation and then I add him as a member :P

**Comment by iJoshuaHD** [comment]
i removed him from the org, invited him as owner. fixed :D 
stupid github for now allowing rank changes on the go.

**Comment by PEMapModder** [comment]
GitHub should allow rank changes without his accepting if he is already in the organization.

**Comment by iksaku** [comment]
@PEMapModder it should... but it doesn't xD

**Pull request merged**
