### PR TITLE
Add "Retro" health bar style

### PR DESCRIPTION
**Pull request by LukeDarling**
Also changed spacing between curly braces.

### CODE REVIEW

**Comment by PEMapModder** [comment]
what...

**Comment by LukeDarling** [comment]
That's cool. I just caused an error in Github!!

**Comment by alejzeis** [comment]
How?

**Comment by LukeDarling** [comment]
"LukeDarling deleted the unknown repository  branch a day ago"

**Comment by alejzeis** [comment]
oh yea.

**Pull request closed without merging**
